### ISSUE TITLE
unit tests fail

### ISSUE THREAD

**Issue by mslacken** [hpcng/warewulf#365]
The unit tests fail on the actual branch in internal/pkg/node/util_test.go

**Comment by MatthewHink** [comment]
Here is some more info. This looks related to the data structure changes.
- This is an access violation.
- n.Kernel is nil here: https://github.com/hpcng/warewulf/blob/95050a44cebeb5fe90cb6ef3a2c3f7e24543b812/internal/pkg/node/constructors.go#L70
- The failing test is using this configuration. Kernel does not appear to be defined: https://github.com/hpcng/warewulf/blob/95050a44cebeb5fe90cb6ef3a2c3f7e24543b812/internal/pkg/node/util_test.go#L10
```
[mhink@rocky warewulf]$ git log -n 1
commit 6c0fd068cc7118b8bf9a3f9e901b179a30474858 (HEAD -> main, origin/main, origin/HEAD)
Author: Christian Goll <cgoll@suse.de>
Date:   Thu Apr 7 17:22:38 2022 +0200

    updated Makefile for v4.3.0-rc1
[mhink@rocky warewulf]$ make test-it
go test -v ./...
?   	github.com/hpcng/warewulf/cmd/bash_completion	[no test files]
?   	github.com/hpcng/warewulf/cmd/config_defaults	[no test files]
?   	github.com/hpcng/warewulf/cmd/man_page	[no test files]
?   	github.com/hpcng/warewulf/cmd/wwclient	[no test files]
?   	github.com/hpcng/warewulf/cmd/wwctl	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwclient	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/configure	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/configure/dhcp	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/configure/nfs	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/configure/ssh	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/configure/tftp	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/container	[no test files]
=== RUN   TestArgsContainerBuild
--- PASS: TestArgsContainerBuild (0.00s)
PASS
ok  	github.com/hpcng/warewulf/internal/app/wwctl/container/build	(cached)
?   	github.com/hpcng/warewulf/internal/app/wwctl/container/delete	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/container/exec	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/container/exec/child	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/container/imprt	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/container/list	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/container/shell	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/container/show	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/container/syncuser	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/kernel	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/kernel/delete	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/kernel/imprt	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/kernel/list	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/node	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/node/add	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/node/console	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/node/delete	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/node/list	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/node/sensors	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/node/set	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/node/status	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/overlay	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/overlay/build	[no test files]
=== RUN   TestArgsOverlayChmod
--- PASS: TestArgsOverlayChmod (0.00s)
PASS
ok  	github.com/hpcng/warewulf/internal/app/wwctl/overlay/chmod	(cached)
?   	github.com/hpcng/warewulf/internal/app/wwctl/overlay/chown	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/overlay/create	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/overlay/delete	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/overlay/edit	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/overlay/imprt	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/overlay/list	[no test files]
=== RUN   TestArgsOverlayMkdir
--- PASS: TestArgsOverlayMkdir (0.00s)
PASS
ok  	github.com/hpcng/warewulf/internal/app/wwctl/overlay/mkdir	(cached)
?   	github.com/hpcng/warewulf/internal/app/wwctl/overlay/show	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/power	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/power/cycle	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/power/off	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/power/on	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/power/reset	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/power/soft	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/power/status	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/profile	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/profile/add	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/profile/delete	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/profile/list	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/profile/set	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/server	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/server/reload	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/server/restart	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/server/start	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/server/status	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/server/stop	[no test files]
?   	github.com/hpcng/warewulf/internal/app/wwctl/version	[no test files]
?   	github.com/hpcng/warewulf/internal/pkg/batch	[no test files]
?   	github.com/hpcng/warewulf/internal/pkg/buildconfig	[no test files]
?   	github.com/hpcng/warewulf/internal/pkg/configure	[no test files]
?   	github.com/hpcng/warewulf/internal/pkg/container	[no test files]
?   	github.com/hpcng/warewulf/internal/pkg/help	[no test files]
?   	github.com/hpcng/warewulf/internal/pkg/kernel	[no test files]
=== RUN   Test_nodeYaml_FindByHwaddr
=== RUN   Test_nodeYaml_FindByHwaddr/emptyString
=== RUN   Test_nodeYaml_FindByHwaddr/noIpString
=== RUN   Test_nodeYaml_FindByHwaddr/intString
=== RUN   Test_nodeYaml_FindByHwaddr/invalidMAC
=== RUN   Test_nodeYaml_FindByHwaddr/validMACNotFound
--- FAIL: Test_nodeYaml_FindByHwaddr (0.00s)
    --- PASS: Test_nodeYaml_FindByHwaddr/emptyString (0.00s)
    --- PASS: Test_nodeYaml_FindByHwaddr/noIpString (0.00s)
    --- PASS: Test_nodeYaml_FindByHwaddr/intString (0.00s)
    --- PASS: Test_nodeYaml_FindByHwaddr/invalidMAC (0.00s)
    --- FAIL: Test_nodeYaml_FindByHwaddr/validMACNotFound (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x56c1aa]

goroutine 11 [running]:
testing.tRunner.func1.2({0x58fde0, 0x6f0230})
	/usr/local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1212 +0x218
panic({0x58fde0, 0x6f0230})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hpcng/warewulf/internal/pkg/node.(*nodeYaml).FindAllNodes(0xc0000e7648)
	/home/mhink/go/src/github.com/hpcng/warewulf/internal/pkg/node/constructors.go:70 +0x36a
github.com/hpcng/warewulf/internal/pkg/node.(*nodeYaml).FindByHwaddr(_, {_, _})
	/home/mhink/go/src/github.com/hpcng/warewulf/internal/pkg/node/util.go:16 +0x85
github.com/hpcng/warewulf/internal/pkg/node.Test_nodeYaml_FindByHwaddr.func1(0xc00008f860)
	/home/mhink/go/src/github.com/hpcng/warewulf/internal/pkg/node/util_test.go:88 +0x8b
testing.tRunner(0xc00008f860, 0xc0000517c0)
	/usr/local/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1306 +0x35a
FAIL	github.com/hpcng/warewulf/internal/pkg/node	0.005s
?   	github.com/hpcng/warewulf/internal/pkg/oci	[no test files]
?   	github.com/hpcng/warewulf/internal/pkg/overlay	[no test files]
?   	github.com/hpcng/warewulf/internal/pkg/pidfile	[no test files]
?   	github.com/hpcng/warewulf/internal/pkg/power	[no test files]
?   	github.com/hpcng/warewulf/internal/pkg/util	[no test files]
?   	github.com/hpcng/warewulf/internal/pkg/version	[no test files]
?   	github.com/hpcng/warewulf/internal/pkg/warewulfconf	[no test files]
?   	github.com/hpcng/warewulf/internal/pkg/warewulfd	[no test files]
?   	github.com/hpcng/warewulf/internal/pkg/wwlog	[no test files]
?   	github.com/hpcng/warewulf/pkg/hostlist	[no test files]
?   	github.com/hpcng/warewulf/test	[no test files]
FAIL
make: *** [Makefile:145: test-it] Error 1
[mhink@rocky warewulf]$ 
```
