### ISSUE TITLE
Node add failure

### ISSUE THREAD

**Issue by MatthewHink** [hpcng/warewulf#366]
This command line used to work. Failure may be due to the data structure changes?
It looks like Kernel isn't getting instantiated if it does not exist here:
https://github.com/hpcng/warewulf/blob/95050a44cebeb5fe90cb6ef3a2c3f7e24543b812/internal/pkg/node/modifiers.go#L63

```
[mhink@rocky warewulf]$ sudo wwctl node add n0000 --netdev eth0 --ipaddr 10.0.8.150  --hwaddr 08:00:27:39:46:70 --discoverable 
Added node: n0000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x5c7b4f]

goroutine 1 [running]:
github.com/hpcng/warewulf/internal/pkg/node.(*nodeYaml).NodeUpdate(_, {{{0xc000495f50, 0x1, 0x1}, {0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, ...}}, ...})
	/home/mhink/go/src/github.com/hpcng/warewulf/internal/pkg/node/modifiers.go:63 +0x38f
github.com/hpcng/warewulf/internal/app/wwctl/node/add.CobraRunE(0x1587da0, {0xc000432f80, 0x1, 0x8})
	/home/mhink/go/src/github.com/hpcng/warewulf/internal/app/wwctl/node/add/main.go:148 +0x18c5
github.com/spf13/cobra.(*Command).execute(0x1587da0, {0xc000432f00, 0x8, 0x8})
	/home/mhink/go/src/github.com/hpcng/warewulf/vendor/github.com/spf13/cobra/command.go:850 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x1584920)
	/home/mhink/go/src/github.com/hpcng/warewulf/vendor/github.com/spf13/cobra/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/home/mhink/go/src/github.com/hpcng/warewulf/vendor/github.com/spf13/cobra/command.go:895
main.main()
	/home/mhink/go/src/github.com/hpcng/warewulf/cmd/wwctl/main.go:13 +0x25
[mhink@rocky warewulf]$ 

```

**Comment by mslacken** [comment]
Yes, the data structures are not initialized at this point. Thanks for getting this
