### ISSUE TITLE
panic during syncusers

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#527]
Encountered this panic:

```
# wwctl container syncuser rocky-8-split
panic: runtime error: index out of range [2] with length 1

goroutine 1 [running]:
github.com/hpcng/warewulf/internal/pkg/container.createPasswdMap({0xd48675, 0xb})
	/builddir/build/BUILD/warewulf-4.3.0/internal/pkg/container/syncuids.go:225 +0x632
github.com/hpcng/warewulf/internal/pkg/container.SyncUids({0x7ffff05f8183, 0xd}, 0x1)
	/builddir/build/BUILD/warewulf-4.3.0/internal/pkg/container/syncuids.go:43 +0x7b
github.com/hpcng/warewulf/internal/app/wwctl/container/syncuser.CobraRunE(0x15e64e0, {0xc00006e520, 0x1, 0x1})
	/builddir/build/BUILD/warewulf-4.3.0/internal/app/wwctl/container/syncuser/main.go:17 +0x6e
github.com/spf13/cobra.(*Command).execute(0x15e64e0, {0xc00006e4f0, 0x1, 0x1})
	/builddir/build/BUILD/warewulf-4.3.0/vendor/github.com/spf13/cobra/command.go:850 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x15e3d80)
	/builddir/build/BUILD/warewulf-4.3.0/vendor/github.com/spf13/cobra/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/warewulf-4.3.0/vendor/github.com/spf13/cobra/command.go:895
main.main()
	/builddir/build/BUILD/warewulf-4.3.0/cmd/wwctl/main.go:13 +0x25
```

Using the RPM from GitHub.

```
# wwctl version
4.3.0-1.git_235c23c
```

I'm still investigating the circumstances.

**Comment by anderbubble** [comment]
This occurred due to a malformed /etc/passwd entry.

```
asdf
x:0:0:root:/root:/bin/bash
```

This was left-over from some testing for #522 and others. [As an aside: it did _not_ prevent me from logging into the affected system.]

Clearly this is a pathological case, and perhaps shouldn't even be addressed in code; but, in theory, I'd argue a panic is always a bug, no matter how pathological the input data.
