### ISSUE TITLE
panic during container import

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#547]
Encountered this panic during `wwctl container import`:

```console
# wwctl container import docker://${REGISTRY}/rocky8:latest rocky-8-228798
Getting image source signatures
Copying blob 1a930d163dca skipped: already exists
Copying blob 5e16be35b2cd skipped: already exists
Copying blob f2eedf5fe300 skipped: already exists
Copying blob b894af96689c done
Copying blob 4684985ed487 done
Copying blob cb3849c68cf5 done
Copying blob d70bba087655 done
Copying blob ade30c7fa38d done
Copying blob 982fb4fae614 done
Copying blob 6bfaa1d6961b done
Copying config d831486136 done
Writing manifest to image destination
Storing signatures
2022/09/27 12:26:36  info unpack layer: sha256:1a930d163dcafa193dc2c3c005d9c220ae1c07a48cad5f7feed0066ada0b998f
2022/09/27 12:26:38  info unpack layer: sha256:5e16be35b2cd8437ee351856e7aa8ee962dd38197fa977bea4d349629148d9e0
panic: d.nx != 0
goroutine 1 [running]:
crypto/sha256.(*digest).checkSum(0xc000018810)
        /usr/lib/golang/src/crypto/sha256/sha256.go:244 +0x1a5
crypto/sha256.(*digest).Sum(0xc0000188c8, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/crypto/sha256/sha256.go:220 +0x85
github.com/opencontainers/go-digest.NewDigest({0xc00019a820, 0x6}, {0xe97578, 0xc0004cf600})
        /share/apps/warewulf/installers/v4.3.0/vendor/github.com/opencontainers/go-digest/digest.go:41 +0x38
github.com/opencontainers/go-digest.(*digester).Digest(0x0)
        /share/apps/warewulf/installers/v4.3.0/vendor/github.com/opencontainers/go-digest/digester.go:39 +0x2b
github.com/opencontainers/umoci/pkg/hardening.(*VerifiedReadCloser).verify(0xc00044a040, {0x0, 0x0})
        /share/apps/warewulf/installers/v4.3.0/vendor/github.com/opencontainers/umoci/pkg/hardening/verified_reader.go:88 +0x42
github.com/opencontainers/umoci/pkg/hardening.(*VerifiedReadCloser).Close(0xc00044a040)
        /share/apps/warewulf/installers/v4.3.0/vendor/github.com/opencontainers/umoci/pkg/hardening/verified_reader.go:175 +0xd7
github.com/opencontainers/umoci/pkg/hardening.(*VerifiedReadCloser).Close(0xc00044a080)
        /share/apps/warewulf/installers/v4.3.0/vendor/github.com/opencontainers/umoci/pkg/hardening/verified_reader.go:164 +0x2d
github.com/opencontainers/umoci/oci/casext.(*Blob).Close(0xc0000001c8)
        /share/apps/warewulf/installers/v4.3.0/vendor/github.com/opencontainers/umoci/oci/casext/blob.go:56 +0x36
github.com/opencontainers/umoci/oci/layer.UnpackRootfs({0xe91678, 0xc00012a010}, {0xea0870, 0xc000113790}, {0xc00003ccc0, _}, {{0x2}, {{0xc0000368d0, 0x28}, {0xc00019a780, ...}, ...}, ...}, ...)
        /share/apps/warewulf/installers/v4.3.0/vendor/github.com/opencontainers/umoci/oci/layer/unpack.go:267 +0x1121
github.com/hpcng/warewulf/internal/pkg/oci.(*puller).Pull(0xc000082cc0, {0xe91678, 0xc00012a010}, {0x7ffe43c04faa, 0xd5164a}, {0xc00003ccc0, 0x31})
        /share/apps/warewulf/installers/v4.3.0/internal/pkg/oci/puller.go:181 +0x909
github.com/hpcng/warewulf/internal/pkg/container.ImportDocker({0x7ffe43c04faa, 0x2b}, {0x7ffe43c04fd6, 0xe}, 0xc0000fe540)
        /share/apps/warewulf/installers/v4.3.0/internal/pkg/container/imprt.go:48 +0x1e8
github.com/hpcng/warewulf/internal/app/wwctl/container/imprt.CobraRunE(0x15e8a60, {0xc000076d80, 0x2, 0x2})
        /share/apps/warewulf/installers/v4.3.0/internal/app/wwctl/container/imprt/main.go:109 +0x415
github.com/spf13/cobra.(*Command).execute(0x15e8a60, {0xc000076d40, 0x2, 0x2})
        /share/apps/warewulf/installers/v4.3.0/vendor/github.com/spf13/cobra/command.go:850 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x15e6d80)
        /share/apps/warewulf/installers/v4.3.0/vendor/github.com/spf13/cobra/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /share/apps/warewulf/installers/v4.3.0/vendor/github.com/spf13/cobra/command.go:895
main.main()
        /share/apps/warewulf/installers/v4.3.0/cmd/wwctl/main.go:13 +0x25
```

**Comment by anderbubble** [comment]
The panic appears to be coming from https://go.googlesource.com/go/+/go1.1.1/src/pkg/crypto/sha256/sha256.go

**Comment by anderbubble** [comment]
It sounds like this occurred during a disk-full event. Can this be caught and handled without exposing a panic / traceback to the end user?

**Comment by mslacken** [comment]
I don't see an easy solution for this as for an diskfull event, we need to know how big an image can get.
