### ISSUE TITLE
erroneous error: 'the overlay template '/etc/hosts.ww' does not exists in 'host' overlay

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#571]
I just encountered this running `development` on an el9 system. I don't think that el9 is relevant here; but just in case.

```bash
[demo@demo2 warewulf]$ sudo wwctl configure hostfile
ERROR  : 'the overlay template '/etc/hosts.ww' does not exists in 'host' overlay

[demo@demo2 warewulf]$ sudo wwctl overlay list host -a
OVERLAY NAME                   FILES/DIRS  
host                           /etc/        
host                           /etc/dhcp/   
host                           /etc/dhcp/dhcpd.conf.ww
host                           /etc/dhcpd.conf
host                           /etc/exports.ww
host                           /etc/hosts.ww
host                           /etc/profile.d/
host                           /etc/profile.d/ssh_setup.csh
host                           /etc/profile.d/ssh_setup.sh
```

**Comment by anderbubble** [comment]
@bschwark can you confirm? I don't think v4.3.0 has a `hostfile` subcommand to `wwctl configure`.

It looks like it was added at https://github.com/hpcng/warewulf/pull/477

**Comment by bschwark** [comment]
@anderbubble Sorry, should've been more specific. This was from dev commit f8d9dbc, which appears like it would have had #477 integrated.

**Comment by anderbubble** [comment]
@mslacken I think I've fixed _this_ problem with the following patch:

```
diff --git a/internal/pkg/configure/hostfile.go b/internal/pkg/configure/hostfile.go
index 15e0b7a..bfb6bb2 100644
--- a/internal/pkg/configure/hostfile.go
+++ b/internal/pkg/configure/hostfile.go
@@ -15,7 +15,9 @@ import (
 Creates '/etc/hosts' from the host template.
 */
 func Hostfile() error {
-       if !(util.IsFile(path.Join(overlay.OverlaySourceDir("host"), "/host/etc/hosts.ww"))) {
+       hostTemplate := path.Join(overlay.OverlaySourceDir("host"), "/etc/hosts.ww")
+       if !(util.IsFile(hostTemplate)) {
                wwlog.Error("'the overlay template '/etc/hosts.ww' does not exists in 'host' overlay")
                os.Exit(1)
        }
@@ -24,13 +26,13 @@ func Hostfile() error {
        hostname, _ := os.Hostname()
        nodeInfo.Id.Set(hostname)
        buffer, backupFile, writeFile, err := overlay.RenderTemplateFile(
-               path.Join(overlay.OverlaySourceDir("host"), "/host/etc/hosts.ww"),
+               hostTemplate,
                tstruct)
        if err != nil {
                wwlog.Error("%s", err)
                os.Exit(1)
        }
-       info, err := os.Stat(path.Join(overlay.OverlaySourceDir("host"), "/host/etc/hosts.ww"))
+       info, err := os.Stat(hostTemplate)
        if err != nil {
                wwlog.Error("%s", err)
                os.Exit(1)
```

But this has exposed another bug:

```
[demo@demo1 warewulf]$ sudo wwctl configure hostfile
panic: reflect: call of reflect.Value.Field on zero Value

goroutine 1 [running]:
reflect.Value.Field({0x0, 0x0, 0x0}, 0xbf2b22)
	/usr/lib/golang/src/reflect/value.go:1198 +0xef
github.com/hpcng/warewulf/internal/pkg/node.(*NodeConf).getterFrom(_, {{{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, ...}}, ...}, ...)
	/home/demo/rpmbuild/BUILD/warewulf-4.3.0/internal/pkg/node/transformers.go:93 +0x21e7
github.com/hpcng/warewulf/internal/pkg/node.(*NodeConf).GetFrom(...)
	/home/demo/rpmbuild/BUILD/warewulf-4.3.0/internal/pkg/node/transformers.go:27
github.com/hpcng/warewulf/internal/pkg/overlay.InitStruct({{{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, ...}}, ...})
	/home/demo/rpmbuild/BUILD/warewulf-4.3.0/internal/pkg/overlay/datastructure.go:87 +0x992
github.com/hpcng/warewulf/internal/pkg/configure.Hostfile()
	/home/demo/rpmbuild/BUILD/warewulf-4.3.0/internal/pkg/configure/hostfile.go:25 +0x136
github.com/hpcng/warewulf/internal/app/wwctl/configure/hostfile.CobraRunE(0x1494a60, {0xd9c59f, 0x0, 0x0})
	/home/demo/rpmbuild/BUILD/warewulf-4.3.0/internal/app/wwctl/configure/hostfile/main.go:9 +0x17
github.com/spf13/cobra.(*Command).execute(0x1494a60, {0x1549180, 0x0, 0x0})
	/home/demo/rpmbuild/BUILD/warewulf-4.3.0/vendor/github.com/spf13/cobra/command.go:850 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x1494280)
	/home/demo/rpmbuild/BUILD/warewulf-4.3.0/vendor/github.com/spf13/cobra/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/home/demo/rpmbuild/BUILD/warewulf-4.3.0/vendor/github.com/spf13/cobra/command.go:895
main.main()
	/home/demo/rpmbuild/BUILD/warewulf-4.3.0/cmd/wwctl/main.go:13 +0x25
```

I think the issue is that we're passing an empty NodeInfo to overlay.InitStruct.

```
        var nodeInfo node.NodeInfo
        tstruct := overlay.InitStruct(nodeInfo)
```

But  I don't know the right way to initialize one in this instance. The only other call to InitStruct is in internal/app/wwctl/overlay/show/main.go.

```
		filteredNodes := node.FilterByName(nodes, []string{NodeName})
		[...]
		tstruct := overlay.InitStruct(filteredNodes[0])
```

**Comment by mslacken** [comment]
@anderbubble Can you please create a PR with your patch as the patch looks malformed on my workstation?

**Comment by mslacken** [comment]
> 

To init a new NodeConf use https://github.com/hpcng/warewulf/blob/385b1569e65dbe5a0eaba487954515ab87cbf674/internal/pkg/node/methods.go#L334

**Comment by anderbubble** [comment]
@mslacken Pull request submitted.

`overlay.InitStruct` expects a `NodeInfo`; but `NewConf` produces a `NodeConf`; so I can't use it to initialize `nodeInfo`. If I do, I get a compile error.

```
../../internal/pkg/configure/hostfile.go:24:31: cannot use nodeInfo (type node.NodeConf) as type node.NodeInfo in argument to overlay.InitStruct
../../internal/pkg/configure/hostfile.go:26:10: nodeInfo.Id undefined (type node.NodeConf has no field or method Id)
```

**Comment by mslacken** [comment]
Just merged in a init function for NodeInfo: https://github.com/hpcng/warewulf/blob/6e85e6ededf5474bd1277051cdbc107d34c4e2b0/internal/pkg/node/methods.go#L344

**Comment by anderbubble** [comment]
Meanwhile, I found a NodeInfo construction for the host in overlay and factored that into a similar constructor in https://github.com/hpcng/warewulf/pull/573/commits/211b91b646e55b49b98191a8d0dd3b5b9ca2971a.

Should I back that out and use `NewInfo()`, or is there any additional value in doing it the way that I did?

**Comment by mslacken** [comment]
I think NewInfo is better right now.
