### ISSUE TITLE
panic listing nodes after adding a node

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#817]
### Version of Warewulf

```console

[janderson@rocky warewulf]$ wwctl version
wwctl version:	 4.4.0-1.git_4eb1314
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.4.0-1.git_4eb1314"
```

### Expected behavior

Should be able to list nodes (or take other actions) after adding a node.

### Actual behavior

Repeatedly got a panic after adding a node. (Happens during delete, too.)

### Steps to reproduce this behavior

```console

[janderson@rocky warewulf]$ sudo wwctl node add asdf5
Added node: asdf5
[janderson@rocky warewulf]$ sudo wwctl node list 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/hpcng/warewulf/internal/pkg/node.(*NodeYaml).FindAllNodes(0x400061cb70)
	/home/janderson/rpmbuild/BUILD/warewulf-4.4.0/internal/pkg/node/constructors.go:216 +0x1568
github.com/hpcng/warewulf/internal/pkg/api/node.NodeList(0x400061fca0)
	/home/janderson/rpmbuild/BUILD/warewulf-4.4.0/internal/pkg/api/node/list.go:24 +0x70
github.com/hpcng/warewulf/internal/app/wwctl/node/list.CobraRunE.func1(0x4000210300?, {0x158cc80?, 0x0?, 0x0?})
	/home/janderson/rpmbuild/BUILD/warewulf-4.4.0/internal/app/wwctl/node/list/main.go:30 +0x124
github.com/spf13/cobra.(*Command).execute(0x4000210300, {0x158cc80, 0x0, 0x0})
	/home/janderson/rpmbuild/BUILD/warewulf-4.4.0/vendor/github.com/spf13/cobra/command.go:916 +0x60c
github.com/spf13/cobra.(*Command).ExecuteC(0x14e72c0)
	/home/janderson/rpmbuild/BUILD/warewulf-4.4.0/vendor/github.com/spf13/cobra/command.go:1044 +0x368
github.com/spf13/cobra.(*Command).Execute(...)
	/home/janderson/rpmbuild/BUILD/warewulf-4.4.0/vendor/github.com/spf13/cobra/command.go:968
main.main()
	/home/janderson/rpmbuild/BUILD/warewulf-4.4.0/cmd/wwctl/main.go:13 +0x30
```

### What OS/distro are you running

```console

[janderson@rocky warewulf]$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.1 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.1 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.1"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
```

### How did you install Warewulf

RPM built from git.

**Comment by anderbubble** [comment]
@mslacken can you look into this? I'm thinking it'll be pretty trivial for you to fix.

Here's an example of the node that's breaking it from nodes.conf. I'm thinking it has something to do with not having any network interfaces; but that's just a guess, going from recent Slack conversation.

```yaml

  asdf5:
    profiles:
    - default
```

**Comment by anderbubble** [comment]
Confirmed, if I update the node to look like this

```yaml

  asdf5:
    profiles:
    - default
    network devices:
      default:
        onboot: "true"
        primary: "true"
```

the panic goes away.

**Comment by mslacken** [comment]
Fixed in actual development.
