### ISSUE TITLE
panic during force container import

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#837]
### Version of Warewulf

What version of Warewulf are you using? Run

```
wwctl version:	 4.4.0-1.git_866348b
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.4.0-1.git_866348b"
```

### Expected behavior

Force-importing a container should overwrite an existing container and import successfully.

### Actual behavior

golang panic.

### Steps to reproduce this behavior

```console

[janderson@rocky warewulf]$ sudo wwctl container import --force docker://ghcr.io/hpcng/warewulf-rockylinux:8 rockylinux-8
Overwriting existing VNFS
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/hpcng/warewulf/internal/pkg/container.syncDB.read(0x4000557228?, {0xdc7d5e, 0xb}, 0x0)
	/home/janderson/rpmbuild/BUILD/warewulf-4.4.0/internal/pkg/container/syncuids.go:206 +0x4f4
github.com/hpcng/warewulf/internal/pkg/container.SyncUids({0xffffeb0df89e?, 0x26?}, 0x0?)
	/home/janderson/rpmbuild/BUILD/warewulf-4.4.0/internal/pkg/container/syncuids.go:59 +0xc4
github.com/hpcng/warewulf/internal/pkg/api/container.ContainerImport(0x4000557c98)
	/home/janderson/rpmbuild/BUILD/warewulf-4.4.0/internal/pkg/api/container/container.go:206 +0x608
github.com/hpcng/warewulf/internal/app/wwctl/container/imprt.CobraRunE(0x14e9520?, {0x40001fad80?, 0x3?, 0x3?})
	/home/janderson/rpmbuild/BUILD/warewulf-4.4.0/internal/app/wwctl/container/imprt/main.go:26 +0xcc
github.com/spf13/cobra.(*Command).execute(0x14e9520, {0x40001fad20, 0x3, 0x3})
	/home/janderson/rpmbuild/BUILD/warewulf-4.4.0/vendor/github.com/spf13/cobra/command.go:916 +0x60c
github.com/spf13/cobra.(*Command).ExecuteC(0x14e72a0)
	/home/janderson/rpmbuild/BUILD/warewulf-4.4.0/vendor/github.com/spf13/cobra/command.go:1044 +0x368
github.com/spf13/cobra.(*Command).Execute(...)
	/home/janderson/rpmbuild/BUILD/warewulf-4.4.0/vendor/github.com/spf13/cobra/command.go:968
main.main()
	/home/janderson/rpmbuild/BUILD/warewulf-4.4.0/cmd/wwctl/main.go:13 +0x30
```

### What OS/distro are you running

Rocky Linux.

### How did you install Warewulf

RPM from develop

**Comment by anderbubble** [comment]
@JasonYangShadow if you've got time.

**Comment by anderbubble** [comment]
Never mind: this is actually in syncuids, which I'm working on; I just wasn't paying attention.

**Comment by mslacken** [comment]
Can't confirm this any more.
@anderbubble if you can't confirm with actual development branch, this one can be closed.

**Comment by JasonYangShadow** [comment]
can not confirm this issue any more. 
```
root@ubuntu:/home/vagrant/warewulf# wwctl container list
  CONTAINER NAME  NODES  KERNEL VERSION                CREATION TIME        MODIFICATION TIME    SIZE     
  rocky8          0      4.18.0-513.9.1.el8_9.aarch64  17 Jan 24 01:54 UTC  01 Jan 70 00:00 UTC  1.2 GiB  
  rockylinux-8    0      4.18.0-513.9.1.el8_9.aarch64  17 Jan 24 01:53 UTC  01 Jan 70 00:00 UTC  1.2 GiB  
root@ubuntu:/home/vagrant/warewulf# wwctl container import --force docker://ghcr.io/hpcng/warewulf-rockylinux:8 rocky8
Overwriting existing VNFS
Copying blob a49f4b3e1553 skipped: already exists  
Copying blob 8b7880b32c88 skipped: already exists  
Copying blob 49a072db3168 skipped: already exists  
Copying blob c43766916271 skipped: already exists  
Copying blob d4cdbc20b5d6 [--------------------------------------] 0.0b / 0.0b
Copying config de197a6d39 done  
Writing manifest to image destination
Storing signatures
2024/01/17 01:55:15  info unpack layer: sha256:a49f4b3e1553c4468c366b42fd1cde2a27729bd7ab13162ad061af2bd1ef9268
2024/01/17 01:55:16  info unpack layer: sha256:8b7880b32c88b97f7738d59c6d76a1f31624007c645be620a1c9720d766b6608
2024/01/17 01:55:21  info unpack layer: sha256:49a072db31682b9f8e8ee50c7bb6f55901d60af154d7f63bed68565f3321f1f5
2024/01/17 01:55:21  info unpack layer: sha256:c43766916271959ec4cc6da5a0455c2c4f1784a7e13081a80461737a20e470e5
2024/01/17 01:55:21  info unpack layer: sha256:d4cdbc20b5d6a3211177be994a6946e43920c8fa826ea0fca0707b23c6179ddc
WARN   : id(7) collision: host(lp) container(halt)
WARN   : add halt to host to resolve conflict
ERROR  : error in user sync, fix error and run 'syncuser' manually: id(7) collision: host(lp) container(halt)
ERROR: error in user sync, fix error and run 'syncuser' manually: id(7) collision: host(lp) container(halt)
root@ubuntu:/home/vagrant/warewulf# 
```

**Comment by anderbubble** [comment]
Yes, sorry; I think this was due to a local change I had made. I should have closed this before.
