### ISSUE TITLE
Node add error on Rocky 8.8

### ISSUE THREAD

**Issue by marcosmazz** [hpcng/warewulf#841]
### Version of Warewulf

What version of Warewulf are you using? Run

`wwctl version`

wwctl version:	 4.4.0-1.git_afcdb21
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.4.0-1.git_afcdb21"

### Expected behavior

```
 wwctl node add node01 --ipaddr 10.10.10.1
```
Node added

### Actual behavior

```
VERBOSE: Opening node configuration file: /etc/warewulf/nodes.conf
VERBOSE: Adding new node: node01
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/hpcng/warewulf/internal/pkg/node.(*NodeYaml).AddNode(_, {_, _})
	/builddir/build/BUILD/warewulf-4.4.0/internal/pkg/node/modifiers.go:28 +0x205
github.com/hpcng/warewulf/internal/pkg/api/node.NodeAdd(0xc000525d18)
	/builddir/build/BUILD/warewulf-4.4.0/internal/pkg/api/node/node.go:42 +0x27f
github.com/hpcng/warewulf/internal/app/wwctl/node/add.CobraRunE(0x1667c80?, {0xc0004a5a40, 0x1, 0x4})
	/builddir/build/BUILD/warewulf-4.4.0/internal/app/wwctl/node/add/main.go:33 +0x292
github.com/spf13/cobra.(*Command).execute(0x1667c80, {0xc0004a5a00, 0x4, 0x4})
	/builddir/build/BUILD/warewulf-4.4.0/vendor/github.com/spf13/cobra/command.go:850 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x16642c0)
	/builddir/build/BUILD/warewulf-4.4.0/vendor/github.com/spf13/cobra/command.go:958 +0x39c
github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/warewulf-4.4.0/vendor/github.com/spf13/cobra/command.go:895
main.main()
	/builddir/build/BUILD/warewulf-4.4.0/cmd/wwctl/main.go:13 +0x25

```

### What OS/distro are you running

```sh
Rocky Linux 8.8 (Green Obsidian)
```

### How did you install Warewulf

rpm from v4.4.0 release

**Comment by marcosmazz** [comment]
My `nodes.conf` was missing an empty list of nodes like the one on the example:

> WW_INTERNAL: 43
> nodeprofiles:
> ...
> **nodes: {}**

**Comment by mslacken** [comment]
Can't  confirm this any more on development. Also the tests in `internal/app/wwctl/node/add/main_test.go` would fail as an empty `nodes.conf` is used there.
